# Assignment 1

In [185]:
from os import getcwd
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
path = getcwd() + "\\resources\\NISPUF17.csv"

In [3]:
with open (path, "r") as file:
    immunes = file.read()

In [5]:
len(immunes)

40531679

In [11]:
data = pd.read_csv(path, index_col='Unnamed: 0')

In [12]:
data.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [17]:
list(data.columns)

['SEQNUMC',
 'SEQNUMHH',
 'PDAT',
 'PROVWT_D',
 'RDDWT_D',
 'STRATUM',
 'YEAR',
 'AGECPOXR',
 'HAD_CPOX',
 'AGEGRP',
 'BF_ENDR06',
 'BF_EXCLR06',
 'BF_FORMR08',
 'BFENDFL06',
 'BFFORMFL06',
 'C1R',
 'C5R',
 'CBF_01',
 'CEN_REG',
 'CHILDNM',
 'CWIC_01',
 'CWIC_02',
 'EDUC1',
 'FRSTBRN',
 'I_HISP_K',
 'INCPORAR',
 'INCPORAR_I',
 'INCPOV1',
 'INCQ298A',
 'LANGUAGE',
 'M_AGEGRP2',
 'MARITAL2',
 'MOBIL_I',
 'NUM_PHONE',
 'NUM_CELLS_HH',
 'NUM_CELLS_PARENTS',
 'RACE_K',
 'RACEETHK',
 'RENT_OWN',
 'SEX',
 'ESTIAP17',
 'EST_GRANT',
 'STATE',
 'D6R',
 'D7',
 'N_PRVR',
 'PROV_FAC',
 'REGISTRY',
 'VFC_ORDER',
 'HEP_BRTH',
 'HEP_FLAG',
 'P_NUHEPX',
 'P_NUHIBX',
 'P_NUHPHB',
 'P_NUMDAH',
 'P_NUMDHI',
 'P_NUMDIH',
 'P_NUMDTA',
 'P_NUMDTP',
 'P_NUMFLU',
 'P_NUMFLUL',
 'P_NUMFLUM',
 'P_NUMFLUN',
 'P_NUMHEA',
 'P_NUMHEN',
 'P_NUMHEP',
 'P_NUMHG',
 'P_NUMHHY',
 'P_NUMHIB',
 'P_NUMHIN',
 'P_NUMHION',
 'P_NUMHM',
 'P_NUMHS',
 'P_NUMIPV',
 'P_NUMMCN',
 'P_NUMMMR',
 'P_NUMMMRX',
 'P_NUMMMX',
 'P_NUMMP',
 'P

In [26]:
data['EDUC1'].unique()

array([4, 3, 1, 2], dtype=int64)

In [33]:
len(data['EDUC1'][data['EDUC1'] == 4])

13656

In [61]:
dictLengths = {dictCorrespondences[x] : len(data['EDUC1'][data['EDUC1'] == x])/data['EDUC1'].count() for x in data['EDUC1'].unique()}

In [62]:
dictLengths

{'college': 0.47974705779026877,
 'more than high school but not college': 0.24588090637625154,
 'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876}

In [48]:
data['EDUC1'].count()

28465

In [63]:
dictCorrespondences = {1 : "less than high school" ,
                       2 : "high school" ,
                       3 : "more than high school but not college" ,
                       4 : "college"}

In [56]:
dictCorrespondences[2]

'high school'

In [68]:
%timeit data['EDUC1'].count()

27.9 µs ± 118 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [69]:
%timeit len(data['EDUC1'])

1.16 µs ± 2.96 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Assignment 2

In [74]:
CBF_01 = data['CBF_01']
CBF_01.unique()

array([ 1,  2, 99, 77], dtype=int64)

In [75]:
P_NUMFLU = data['P_NUMFLU']
P_NUMFLU.unique()

array([nan,  3.,  0.,  2.,  1.,  4.,  5.,  6.])

In [87]:
maskYes = CBF_01 == 1 #Yes
maskNo = CBF_01 == 2 #No

In [88]:
maskNo

1        False
2         True
3         True
4         True
5        False
         ...  
28461     True
28462    False
28463    False
28464     True
28465    False
Name: CBF_01, Length: 28465, dtype: bool

In [89]:
maskYes

1         True
2        False
3        False
4        False
5         True
         ...  
28461    False
28462     True
28463     True
28464    False
28465     True
Name: CBF_01, Length: 28465, dtype: bool

In [100]:
sum(P_NUMFLU[maskYes].dropna())/len(P_NUMFLU[maskYes].dropna())

1.8799187420058687

In [99]:
sum(P_NUMFLU[maskNo].dropna())/len(P_NUMFLU[maskNo].dropna())

1.5963945918878317

In [101]:
sum(P_NUMFLU[maskYes].fillna(0.0))/len(P_NUMFLU[maskYes])

1.0298833518816206

In [102]:
sum(P_NUMFLU[maskNo].fillna(0.0))/len(P_NUMFLU[maskNo])

0.7804161566707466

In [108]:
%timeit sum(P_NUMFLU[maskYes].dropna())

780 µs ± 4.14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [109]:
%timeit P_NUMFLU[maskYes].dropna().sum()

376 µs ± 879 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Assignment 3

In [117]:
SEX = data['SEX']
SEX.unique()

array([1, 2], dtype=int64)

In [118]:
P_NUMVRC = data['P_NUMVRC']
P_NUMVRC.unique()

array([nan,  1.,  0.,  2.,  3.])

In [119]:
HAD_CPOX = data['HAD_CPOX']
HAD_CPOX.unique()

array([ 2,  1, 77, 99], dtype=int64)

In [166]:
maskSex = SEX == 1
maskHadCPox = HAD_CPOX == 1
maskNoCPox = HAD_CPOX == 2
maskVaccCPox = P_NUMVRC >= 1

In [173]:
YesVaccYesCPox = HAD_CPOX[maskVaccCPox][maskHadCPox]
YesVaccNoCPox = HAD_CPOX[maskVaccCPox][maskNoCPox]

In [181]:
YesVaccYesCPoxMales = YesVaccYesCPox[maskSex]
YesVaccYesCPoxFemales = YesVaccYesCPox[~maskSex]
YesVaccNoCPoxMales = YesVaccNoCPox[maskSex]
YesVaccNoCPoxFemales = YesVaccNoCPox[~maskSex]

In [180]:
len(YesVaccYesCPoxFemales)

53

In [179]:
len(YesVaccYesCPoxMales)

68

In [182]:
len(YesVaccYesCPoxFemales) / len(YesVaccNoCPoxFemales)

0.0077918259335489565

In [183]:
len(YesVaccYesCPoxMales) / len(YesVaccNoCPoxMales)

0.009675583380762664

# Assignment 4

In [195]:
maskCPox = HAD_CPOX <= 2

In [194]:
maskVacc = P_NUMVRC >= 0

In [196]:
HAD_CPOX[maskCPox][maskVacc]

4        2
5        2
7        2
8        2
9        1
        ..
28447    2
28448    2
28450    2
28453    2
28455    2
Name: HAD_CPOX, Length: 15286, dtype: int64

In [197]:
P_NUMVRC[maskCPox][maskVacc]

4        1.0
5        0.0
7        1.0
8        0.0
9        0.0
        ... 
28447    1.0
28448    1.0
28450    1.0
28453    1.0
28455    1.0
Name: P_NUMVRC, Length: 15286, dtype: float64

In [198]:
corr, pval=stats.pearsonr(HAD_CPOX[maskCPox][maskVacc],P_NUMVRC[maskCPox][maskVacc])

In [199]:
corr,pval

(0.07044873460147873, 2.7780263182892073e-18)

In [201]:
data['VRC1_AGE'].unique()

array([nan, 12., 13., 10., 24., 15., 16., 20., 14., 18., 19., 17., 32.,
       22., 21., 33., 30., 25., 38., 26., 11., 34., 29., 28., 23.,  4.,
       31.,  6., 36., 27.,  9., 37.,  0.,  7.,  2., 35.,  3.,  5., 39.])